// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zthcdqspajnovfxgccgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0aGNkcXNwYWpub3ZmeGdjY2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDQ4MzIsImV4cCI6MjA1OTg4MDgzMn0.fhotz3WdD_9gahlEcgvjt976iSW5FhRUFhxpl23WbmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);